apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: harness_basic
  title: Call a pipeline via Harness IDP
  description: Use IDP to call a harness pipeline and pass it some variables
  tags:
    - example
spec:
  owner: david.stewart
  type: environment
  parameters:
    - title: Project and Repo Details
      required:
        - owner
        - github_repo
      properties:
        owner:
          title: Choose the Owner
          type: string
          ui:field: OwnerPicker
          ui:options: null
        github_repo:
          title: What App/Repo will this infra be associated with?
          type: string
          description: someRepoName
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
    - title: Pass Variables Here
      properties:
        exampleVar:
          title: Select an option
          type: array
          items:
            type: string
            enum:
            - Option1
            - Option2
            - Option3
          default:
            - Option1
      ui:
        exampleVar:
          title: Select options
          multi: true
  steps: 
    -id: transformVariables
    name: transform Variables
    action: script
    input: 
      content: |
        // Convert the array to a comma-separated string
        const exampleVarString = parameters.exampleVar.join(',');

        // Set the converted string as a new parameter
        parameters.exampleVarString = exampleVarString;
    output: {}
  
  steps:
    - id: trigger
      name: Call a harness pipeline, and pass the variables from above
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/SAsyUUHTTImuYSZ35HPDvw/home/orgs/default/projects/DavidStewart_Sandbox/pipelines/IDP_Pipeline_Example/pipeline-studio/?storeType=INLINE
        inputset:
          exampleVar: ${{ paramaters.exampleVarString }}
          owner: ${{ parameters.owner }}
        apikey: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
